[package]
name = "age-calc-web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.3"
actix-web = "4.1"
serde = { version = "1.0", features = ["derive"] }
